services:
  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.26.1
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    read_only: true
    privileged: false
    env_file:
      - .env
    volumes:
      - "${DIMP_DUP_YAML_PATH:-./dimp_dup_base.yaml}:/opt/fhir-pseudonymizer/dimp_dup_base.yaml:ro"
    ports:
      - "127.0.0.1:8083:8080"
