services:
  fhir-validator:
    image: ghcr.io/medizininformatik-initiative/mii-fhir-validator:0.0.1-alpha.4
    ports:
      - "8080:8080"
    env_file:
      - .env
    extra_hosts:
      - "terminology.localhost:host-gateway"
    volumes:
      - ./igs:/igs:ro
      - ./config/fhir-settings.json:/app/fhir-settings.json:ro
      - ../auth/cert.pem:/etc/nginx/certs/self-signed.crt:ro
      - fhir-package-cache:/root/.fhir/packages
    restart: unless-stopped

volumes:
  fhir-package-cache:
