name: CI

on:
  push:
    branches:
    - main
    - develop
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:
    branches:
    - main
    - develop

env:
  DATA_PORTAL_COMPOSE_PROJECT: test

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Check shell scripts
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: .github/scripts

  test-data-node-e2e:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install aether
      run: .github/scripts/install-aether.sh

    - name: Set up Data Node
      run: .github/scripts/setup-data-node.sh

    - name: Get MII testdata
      working-directory: data-node
      run: ./get-mii-testdata.sh

    - name: Upload testdata
      run: data-node/upload-testdata.sh

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install e2e test dependencies
      run: pip install -r .github/e2e-tests/requirements.txt

    - name: Run e2e tests
      run: pytest .github/e2e-tests
